on:
  push:
    branches:
      - develop
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO }}

      - name: 📦 Install dependencies
        run: npm install

      - name: 🚀 Create update
        run: EXPO_PUBLIC_API_KEY=hola eas update --auto --non-interactive
