on:
  push:
    branches:
      - develop
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO }}

      - name: 📦 Install dependencies
        run: npm install

      - name: 🚀 Create update
        run: EXPO_PUBLIC_API_KEY=${{ secrets.EXPO_PUBLIC_API_KEY }} EXPO_PUBLIC_APP_ID=${{ secrets.EXPO_PUBLIC_APP_ID }} EXPO_PUBLIC_AUTH_DOMAIN=${{ secrets.EXPO_PUBLIC_AUTH_DOMAIN }} EXPO_PUBLIC_MEASUREMENT_ID=${{ secrets.EXPO_PUBLIC_MEASUREMENT_ID }}  EXPO_PUBLIC_MESSAGING_SENDER_ID=${{ secrets.EXPO_PUBLIC_MESSAGING_SENDER_ID }}  EXPO_PUBLIC_PROJECT_ID=${{ secrets.EXPO_PUBLIC_PROJECT_ID }} EXPO_PUBLIC_SERVER_LOCAL=${{ secrets.EXPO_PUBLIC_SERVER_LOCAL }} EXPO_PUBLIC_STORAGE_BUCKET=${{ secrets.EXPO_PUBLIC_STORAGE_BUCKET }} eas update --auto --non-interactive
